CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

CONFIG_ZMK_DISPLAY=y

CONFIG_USB_DEVICE_STACK=y
CONFIG_ZMK_USB=y
CONFIG_ZMK_HID_INDICATORS=y

CONFIG_BT=y

CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

CONFIG_USB_DEVICE_PRODUCT="MurphPad"
